### ISSUE TITLE
Issue with the docs

### ISSUE THREAD

**Issue by de-farias** [piotrmurach/strings#13]
TL;DR: The docs mention the `:separator` option and shows an example, but the example doesn't use the `:separator` option.

I'll just post the image:

![Screenshot from 2020-08-19 10-57-46](https://user-images.githubusercontent.com/12251182/90644487-27e41c80-e20b-11ea-80b4-40bf66459e9c.png)

Nice work, by the way!

**Comment by piotrmurach** [comment]
Thank you Inácio for opening this issue. The docs are updated.
