### ISSUE TITLE
Support for dasherize, underscore, classify, and perhaps more

### ISSUE THREAD

**Issue by bryanp** [piotrmurach/strings#15]
I often find myself reimplementing patterns for dasherizing, underscoring, and classifying strings (this not an exhaustive list, there are plenty more). Would this library be an appropriate place for these types of functions to live? If not, do you have plans for a `strings-*` library where function like these would fit?

**Comment by piotrmurach** [comment]
There is the [strings-case](https://github.com/piotrmurach/strings-case) project that may partially satisfy your needs(`dashcase`, `underscore` etc.). As for the plan for `strings` gem, it will become more of a meta gem without any functionality in the near future. I want to tease out all the bits out like `truncation` and `wrapping` to separate gems. Currently, I'm about 95% done with upgrading all the `tty` gems and the `tty` project itself and hope to finish it very soon. Once this is done, I'll shift my focus to the `strings` project and the extraction of the mentioned functionality. I'd like all the `strings-*` gems to have consistent API, especially when it comes to configuration. I'm more than happy to add new components to the [current list](https://github.com/piotrmurach/strings#4-components).

**Comment by bryanp** [comment]
Oh, excellent I hadn't seen `strings-case`. I think that supports my current needs!
